version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.yarn/cache
      - /usr/src/app/prisma/migrations
    ports:
      - 3000:3000
    command: yarn run dev
